# Tugas 3 implementasi Latent Directlet allocation (LDA)

Lakukan implementasi kan lda pada data abstrack:

dengan k=3  alhpa=0.1 beta=0.2

library di scikit-learn

doc_topic_prior float, default=None

Prior of document topic distribution theta. If the value is None, defaults to 1 / n_components.

In [1], this is called alpha.

topic_word_priorfloat, default=None

Prior of topic word distribution beta. If the value is None, defaults to 1 / n_components. In [1], this is called eta.

output adalah :

- proporsi topik pada dokumen

- distribusi kata pada topik

In [1]:
import pandas as pd
from sklearn.decomposition import LatentDirichletAllocation

In [8]:
df_tf = pd.read_excel("/content/drive/MyDrive/ppw/tugas/data-tugas/df_tf.xlsx")
df_tf

aalysis  aam  abad  abadi  ability  abjad  absensi  absolut  absolute  \
0          0    0     0      0        0      0        0        0         0   
1          0    0     0      0        0      0        0        0         0   
2          0    0     0      0        0      0        0        0         0   
3          0    0     0      0        0      0        0        0         0   
4          0    0     0      0        0      0        0        0         0   
..       ...  ...   ...    ...      ...    ...      ...      ...       ...   
853        0    0     0      0        0      0        0        0         0   
854        0    0     0      0        0      0        0        0         0   
855        0    0     0      0        0      0        0        0         0   
856        0    0     0      0        0      0        0        0         0   
857        0    0     0      0        0      0        0        0         0   

     abstract  ...  zara  zat  zcz  zf  zona  zone  zoning  zoom  zucara  \
0           0  ...     0    0    0   0     0     0       0     0       0   
1           0  ...     0    0    0   0     0     0       0     0       0   
2           0  ...     0    0    0   0     0     0       0     0       0   
3           0  ...     0    0    0   0     0     0       0     0       0   
4           0  ...     0    0    0   0     0     0       0     0       0   
..        ...  ...   ...  ...  ...  ..   ...   ...     ...   ...     ...   
853         0  ...     0    0    0   0     0     0       0     0       0   
854         0  ...     0    0    0   0     0     0       0     0       0   
855         0  ...     0    0    0   0     0     0       0     0       0   
856         0  ...     0    0    0   0     0     0       0     0       0   
857         0  ...     0    0    0   0     0     0       0     0       0   

     zungu  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
853      0  
854      0  
855      0  
856      0  
857      0  

[858 rows x 8427 columns]


Diketahui dan diperintahkan bahwa harus,

**k=3 alpHa=0.1 beta=0.2**

Kita implementasikan di library LDA dengan,

n_components=3,  topic_word_prior=0.1, doc_topic_prior=0.2

In [9]:
lda = LatentDirichletAllocation(n_components=3, doc_topic_prior=0.2, topic_word_prior=0.1,random_state=42,max_iter=1)
lda_top=lda.fit_transform(df_tf)

In [10]:
print(lda_top.shape)  # (no_of_doc,no_of_topics)
print(lda_top)

(858, 3)
[[0.12865185 0.00236316 0.86898499]
 [0.00182329 0.00181781 0.9963589 ]
 [0.00172526 0.99652485 0.00174989]
 ...
 [0.99745825 0.00127282 0.00126893]
 [0.00153044 0.99694874 0.00152082]
 [0.99554297 0.00223002 0.00222701]]


In [11]:
#bobot setiap topik terhadap dokumen
bobot = pd.DataFrame(lda_top, columns=['Topik 1','Topik 2','Topik 3'])
bobot

Topik 1   Topik 2   Topik 3
0    0.128652  0.002363  0.868985
1    0.001823  0.001818  0.996359
2    0.001725  0.996525  0.001750
3    0.702589  0.002729  0.294683
4    0.002357  0.995259  0.002384
..        ...       ...       ...
853  0.472334  0.001645  0.526021
854  0.002345  0.995316  0.002338
855  0.997458  0.001273  0.001269
856  0.001530  0.996949  0.001521
857  0.995543  0.002230  0.002227

[858 rows x 3 columns]

In [12]:
print(lda.components_)
print(lda.components_.shape)  # (no_of_topics*no_of_words)

[[0.1648078  1.5256322  0.10006905 ... 0.69848206 0.8296641  0.99189367]
 [0.95059889 0.66160664 0.34015165 ... 0.16245608 0.1000648  0.10004677]
 [0.18459331 0.11276116 1.8597793  ... 2.43906186 0.3702711  0.20805956]]
(3, 8427)


In [13]:
#bobot setiap kata terhadap topik
label=[]
for i in range (1,(lda.components_.shape[1]+1)):
  masukan = df_tf.columns[i-1]
  label.append(masukan)
VT_tabel = pd.DataFrame(lda.components_,columns=label)
VT_tabel.rename(index={0:"Topik 1",1:"Topik 2",2:"Topik 3"}).transpose()

Topik 1   Topik 2   Topik 3
aalysis  0.164808  0.950599  0.184593
aam      1.525632  0.661607  0.112761
abad     0.100069  0.340152  1.859779
abadi    1.260591  0.100120  0.939289
ability  0.638600  0.561337  0.100063
...           ...       ...       ...
zone     2.051761  1.148008  0.100231
zoning   2.491565  1.708271  0.100164
zoom     0.698482  0.162456  2.439062
zucara   0.829664  0.100065  0.370271
zungu    0.991894  0.100047  0.208060

[8427 rows x 3 columns]