## UAS Pencarian & Penambangan Web

## 210411100112 - Okhi Sahrul Barkah

## Link Aplikasi :
https://topic-modelling-app-n39rhvd7cvu3ms9czhqiu7.streamlit.app/

## Mengaplikasikan di Semua Dataset

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd

In [4]:
data = pd.read_csv("/content/drive/MyDrive/ppw/tugas/data_tugas5/data_label.csv")
data = data.dropna()
data = data.reset_index(drop=True)

In [5]:
df = data[['Content', 'Label']]
df

Content    Label
0    ASAPI Francesco Bagnaia di MotoGP Jepang 2023,...    Sport
1    EKO Yuli Irawan mengucapkan permintaan maafnya...    Sport
2    MOTEGI - Marc Marquez girang setelah bisa naik...    Sport
3    KLASEMEN sementara perolehan medali Asian Game...    Sport
4    HASIL Asian Games 2023 akan dibahas di sini. T...    Sport
..                                                 ...      ...
987  JAKARTA - Segini besaran uang makan dan uang l...  Politik
988  JAKARTA – Aturan Rancangan Peraturan Pemerinta...  Politik
989  JAKARTA - Menteri Pertanian Amran Sulaiman men...  Politik
990  JAKARTA - Calon Presiden Partai Perindo Ganjar...  Politik
991  JAKARTA - SKK Migas menyatakan potensi harta k...  Politik

[992 rows x 2 columns]

## Pre - Processing

In [6]:
#install library
!pip install sastrawi
!pip install swifter
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 3.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 8.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for swifter: filename=swifter-1.4.0-py3-none-any.whl size=16506 sha256=565ba7478a74bfd11f0bde20968c621a473373709c44bff006e9424b89d4be50
  Stored in directory: /root/.cache/pip/wheels/e4/cf/51/0904952972ee2c7aa3709437065278dc534ec1b8d2ad41b443
Successfully built swifter


In [7]:
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


### Menghilangkan Tanda Baca

In [8]:
#Remove Puncutuation
clean_tag = re.compile('@\S+')
clean_url = re.compile('https?:\/\/.*[\r\n]*')
clean_hastag = re.compile('#\S+')
clean_symbol = re.compile('[^a-zA-Z]')
def clean_punct(text):
    text = clean_tag.sub('', str(text))
    text = clean_url.sub('', text)
    text = clean_hastag.sub(' ', text)
    text = clean_symbol.sub(' ', text)
    return text
# Buat kolom tambahan untuk data description yang telah diremovepunctuation
preprocessing = df['Content'].apply(clean_punct)
clean=pd.DataFrame(preprocessing)
clean

Content
0    ASAPI Francesco Bagnaia di MotoGP Jepang      ...
1    EKO Yuli Irawan mengucapkan permintaan maafnya...
2    MOTEGI   Marc Marquez girang setelah bisa naik...
3    KLASEMEN sementara perolehan medali Asian Game...
4    HASIL Asian Games      akan dibahas di sini  T...
..                                                 ...
987  JAKARTA   Segini besaran uang makan dan uang l...
988  JAKARTA   Aturan Rancangan Peraturan Pemerinta...
989  JAKARTA   Menteri Pertanian Amran Sulaiman men...
990  JAKARTA   Calon Presiden Partai Perindo Ganjar...
991  JAKARTA   SKK Migas menyatakan potensi harta k...

[992 rows x 1 columns]

In [9]:
import joblib

# Simpan fungsi clean_punct menggunakan joblib
joblib.dump(clean_punct, 'clean_punct_function.joblib')


['clean_punct_function.joblib']

### Tokenisasi

In [10]:
from nltk.tokenize import word_tokenize

def tokenize_text(text_data):
    tokenized_data = []
    for text in text_data:
        tokens = word_tokenize(text)
        tokenized_data.append(tokens)
    return tokenized_data

# Menggunakan fungsi tokenize_text untuk tokenisasi
data_clean = []
tokenize = tokenize_text(preprocessing)

for tokendata in tokenize:
    print(tokendata)


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)




['JAKARTA', 'Segini', 'besaran', 'uang', 'makan', 'dan', 'uang', 'lauk', 'pauk', 'PNS', 'PPPK', 'tahun', 'Seperti', 'yang', 'diketahui', 'seorang', 'Pegawai', 'Negeri', 'Sipil', 'PNS', 'menerima', 'beberapa', 'fasilitas', 'yang', 'diberikan', 'oleh', 'negara', 'beserta', 'tunjangan', 'tunjangannya', 'Tak', 'hanya', 'itu', 'PNS', 'juga', 'mendapatkan', 'uang', 'makan', 'Dalam', 'hal', 'ini', 'pemberian', 'anggaran', 'telah', 'diatur', 'melalui', 'Kementerian', 'Keuangan', 'Kemenkeu', 'berdasarkan', 'Peraturan', 'Menteri', 'Keuangan', 'PMK', 'Nomor', 'Tahun', 'tentang', 'Standar', 'Biaya', 'Masukan', 'Tahun', 'BACA', 'JUGA', 'SKD', 'CPNS', 'Kemenag', 'Dimulai', 'Besok', 'Cek', 'Jadwal', 'hingga', 'Lokasi', 'Tes', 'di', 'SiniPeraturan', 'ini', 'mencantumkan', 'beberapa', 'ketentuan', 'seperti', 'standar', 'biaya', 'makan', 'bagi', 'PNS', 'yang', 'menyesuaikan', 'pada', 'setiap', 'golongannya', 'hingga', 'mencapai', 'Rp', 'ribu', 'per', 'bulannya', 'Namun', 'besaran', 'rincian', 'uang', '

In [11]:
import joblib

# Simpan fungsi tokenize_text menggunakan joblib
joblib.dump(tokenize_text, 'tokenize_text_function.joblib')


['tokenize_text_function.joblib']

### Stopword Removal

In [ ]:
from nltk.corpus import stopwords

def remove_stopwords(tokenized_data):
    stopword_removed = []
    stop_words = set(stopwords.words('indonesian'))

    for tokens in tokenized_data:
        removed = [word for word in tokens if word not in stop_words]
        stopword_removed.append(removed)
        print(removed)

    return stopword_removed

# Menggunakan fungsi remove_stopwords untuk menghapus stopwords
stopword = remove_stopwords(tokenize)


In [13]:
import joblib

# Simpan fungsi remove_stopwords menggunakan joblib
joblib.dump(remove_stopwords, 'remove_stopwords_function.joblib')


['remove_stopwords_function.joblib']

### Merubah Isi dari Content

In [14]:
join=[]
for i in range(len(stopword)):
  joinkata = ' '.join(stopword[i])
  join.append(joinkata)

hasilpreproses = pd.DataFrame(join, columns=['Content'])
hasilpreproses

Content
0    ASAPI Francesco Bagnaia MotoGP Jepang Jorge Ma...
1    EKO Yuli Irawan permintaan maafnya gagal sumba...
2    MOTEGI Marc Marquez girang podium kalinya musi...
3    KLASEMEN perolehan medali Asian Games Minggu W...
4    HASIL Asian Games dibahas Timnas Basket Putri ...
..                                                 ...
987  JAKARTA Segini besaran uang makan uang lauk pa...
988  JAKARTA Aturan Rancangan Peraturan Pemerintah ...
989  JAKARTA Menteri Pertanian Amran Sulaiman salah...
990  JAKARTA Calon Presiden Partai Perindo Ganjar P...
991  JAKARTA SKK Migas potensi harta karun minyak g...

[992 rows x 1 columns]

## TF

In [17]:
import numpy as np

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(np.array(hasilpreproses['Content']))

In [19]:
tf = vectorizer.get_feature_names_out()
tf

array(['aa', 'aakarshi', 'aan', ..., 'zona', 'zu', 'zulkifli'],
      dtype=object)

In [20]:
tf_array = X.toarray()
print(tf_array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
df_tf= pd.DataFrame(tf_array, columns = tf)
df_tf

aa  aakarshi  aan  aaron  abad  abadi  abang  abc  abdi  abdul  ...  zhu  \
0     0         0    0      0     0      0      0    0     0      0  ...    0   
1     0         0    0      0     0      0      0    0     0      0  ...    0   
2     0         0    0      0     0      0      0    0     0      0  ...    0   
3     0         0    0      0     0      0      0    0     0      0  ...    0   
4     0         0    0      0     0      0      0    0     0      0  ...    0   
..   ..       ...  ...    ...   ...    ...    ...  ...   ...    ...  ...  ...   
987   0         0    0      0     0      0      0    0     5      0  ...    0   
988   0         0    0      0     0      0      0    0     0      0  ...    0   
989   0         0    0      0     0      0      0    0     0      0  ...    0   
990   0         0    0      0     0      0      0    0     0      0  ...    0   
991   0         0    0      0     0      0      0    0     0      0  ...    0   

     zhuhai  zigi  zii  zilberman  zinedine  zion  zona  zu  zulkifli  
0         0     0    0          0         0     0     0   0         0  
1         0     0    0          0         0     0     0   0         0  
2         0     0    0          0         0     0     0   0         0  
3         0     0    0          0         0     0     0   0         0  
4         0     0    0          0         0     0     0   0         0  
..      ...   ...  ...        ...       ...   ...   ...  ..       ...  
987       0     0    0          0         0     0     0   0         0  
988       0     0    0          0         0     0     0   0         0  
989       0     0    0          0         0     0     0   0         0  
990       0     0    0          0         0     0     0   0         0  
991       0     0    0          0         0     0     0   0         0  

[992 rows x 8616 columns]

In [22]:
df_tf.to_csv('df_tf.csv', index=False)

## TF - IDF

TF-IDF adalah singkatan dari “Term Frequency-Inverse Document Frequency” dalam pemrosesan bahasa alami dan analisis teks. Ini adalah metode statistik yang digunakan untuk mengukur pentingnya sebuah kata atau istilah dalam suatu dokumen terhadap koleksi dokumen yang lebih besar.

In [23]:
tr_idf_model  = TfidfVectorizer()
tf_idf_vector = tr_idf_model.fit_transform(hasilpreproses['Content'])

In [24]:
tf_idf_array = tf_idf_vector.toarray()
print(tf_idf_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
words_set = tr_idf_model.get_feature_names_out()
print(words_set)

['aa' 'aakarshi' 'aan' ... 'zona' 'zu' 'zulkifli']


In [26]:
df_tf_idf = pd.DataFrame(tf_idf_array, columns = words_set)
df_tf_idf

aa  aakarshi  aan  aaron  abad  abadi  abang  abc      abdi  abdul  ...  \
0    0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
1    0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
2    0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
3    0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
4    0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
..   ...       ...  ...    ...   ...    ...    ...  ...       ...    ...  ...   
987  0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.029697    0.0  ...   
988  0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
989  0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
990  0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   
991  0.0       0.0  0.0    0.0   0.0    0.0    0.0  0.0  0.000000    0.0  ...   

     zhu  zhuhai  zigi  zii  zilberman  zinedine  zion  zona   zu  zulkifli  
0    0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
1    0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
2    0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
3    0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
4    0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
..   ...     ...   ...  ...        ...       ...   ...   ...  ...       ...  
987  0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
988  0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
989  0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
990  0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  
991  0.0     0.0   0.0  0.0        0.0       0.0   0.0   0.0  0.0       0.0  

[992 rows x 8616 columns]

## Latent Dirichlet Allocation (LDA)

In [28]:
from sklearn.decomposition import LatentDirichletAllocation
import numpy as np

lda_results = []

for n in range(1, 51):
    lda = LatentDirichletAllocation(n_components=n, doc_topic_prior=0.2, topic_word_prior=0.1, random_state=42, max_iter=1)
    lda_top = lda.fit_transform(df_tf_idf)
    lda_results.append(lda_top)

In [29]:
n_components = 50
column_names = [f'Topik {i+1}' for i in range(n_components)]
topik50 = pd.DataFrame(lda_top, columns=column_names)

In [30]:
topik50

Topik 1   Topik 2   Topik 3   Topik 4   Topik 5   Topik 6   Topik 7  \
0    0.010541  0.010058  0.010283  0.010234  0.010190  0.010260  0.010638   
1    0.010878  0.010705  0.010814  0.010739  0.011065  0.010786  0.011038   
2    0.010930  0.010676  0.010735  0.010709  0.010747  0.010958  0.010802   
3    0.011589  0.011152  0.011354  0.011313  0.011647  0.011335  0.011333   
4    0.012725  0.012265  0.012644  0.012507  0.014421  0.012632  0.012964   
..        ...       ...       ...       ...       ...       ...       ...   
987  0.012829  0.013183  0.012703  0.012715  0.012709  0.012741  0.012709   
988  0.010602  0.010551  0.010551  0.010577  0.010542  0.010597  0.010583   
989  0.403783  0.012143  0.012152  0.012493  0.012255  0.012147  0.012166   
990  0.011281  0.011228  0.011256  0.011260  0.011241  0.011291  0.011277   
991  0.011075  0.011028  0.011050  0.011021  0.011025  0.011025  0.011045   

      Topik 8   Topik 9  Topik 10  ...  Topik 41  Topik 42  Topik 43  \
0    0.010085  0.010298  0.452646  ...  0.010705  0.010103  0.010050   
1    0.011118  0.010816  0.010785  ...  0.010704  0.010738  0.010699   
2    0.010791  0.010781  0.011173  ...  0.010938  0.010717  0.010704   
3    0.011244  0.011610  0.011292  ...  0.011161  0.011306  0.011141   
4    0.012734  0.012664  0.012615  ...  0.012419  0.012428  0.012279   
..        ...       ...       ...  ...       ...       ...       ...   
987  0.012713  0.012711  0.012705  ...  0.012734  0.012750  0.012701   
988  0.010536  0.010580  0.010527  ...  0.010566  0.010747  0.010529   
989  0.012158  0.012283  0.012148  ...  0.012179  0.012146  0.012149   
990  0.011239  0.011295  0.011232  ...  0.011510  0.011231  0.011228   
991  0.011059  0.011052  0.011014  ...  0.011112  0.011078  0.011018   

     Topik 44  Topik 45  Topik 46  Topik 47  Topik 48  Topik 49  Topik 50  
0    0.010358  0.010067  0.010096  0.010115  0.010197  0.010085  0.010259  
1    0.010769  0.010716  0.010831  0.010966  0.010831  0.010798  0.010828  
2    0.010797  0.010720  0.010760  0.010759  0.010904  0.010734  0.010826  
3    0.011219  0.011161  0.011224  0.011192  0.011289  0.011196  0.011193  
4    0.012363  0.012389  0.012460  0.012396  0.013103  0.012323  0.012651  
..        ...       ...       ...       ...       ...       ...       ...  
987  0.012703  0.012696  0.012702  0.012699  0.012701  0.012720  0.012791  
988  0.010548  0.010529  0.010533  0.010544  0.010527  0.010602  0.010555  
989  0.012153  0.012145  0.012164  0.012157  0.012146  0.012145  0.012161  
990  0.011266  0.011225  0.011247  0.011234  0.011229  0.011250  0.011441  
991  0.011028  0.011008  0.011029  0.011080  0.011131  0.011028  0.011084  

[992 rows x 50 columns]

In [31]:
df_gabungan = pd.concat([topik50, df['Label']], axis=1)

print(df_gabungan)

      Topik 1   Topik 2   Topik 3   Topik 4   Topik 5   Topik 6   Topik 7  \
0    0.010541  0.010058  0.010283  0.010234  0.010190  0.010260  0.010638   
1    0.010878  0.010705  0.010814  0.010739  0.011065  0.010786  0.011038   
2    0.010930  0.010676  0.010735  0.010709  0.010747  0.010958  0.010802   
3    0.011589  0.011152  0.011354  0.011313  0.011647  0.011335  0.011333   
4    0.012725  0.012265  0.012644  0.012507  0.014421  0.012632  0.012964   
..        ...       ...       ...       ...       ...       ...       ...   
987  0.012829  0.013183  0.012703  0.012715  0.012709  0.012741  0.012709   
988  0.010602  0.010551  0.010551  0.010577  0.010542  0.010597  0.010583   
989  0.403783  0.012143  0.012152  0.012493  0.012255  0.012147  0.012166   
990  0.011281  0.011228  0.011256  0.011260  0.011241  0.011291  0.011277   
991  0.011075  0.011028  0.011050  0.011021  0.011025  0.011025  0.011045   

      Topik 8   Topik 9  Topik 10  ...  Topik 42  Topik 43  Topik 44  \
0  

In [32]:
df_gabungan = df_gabungan.dropna()

## Naive Bayes

In [33]:
print(data['Label'].unique())

['Sport' 'Finance' 'Politik']


In [34]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Pisahkan fitur dan label dari DataFrame yang telah digabungkan
X = df_gabungan.drop(columns=['Label']).values
y = df_gabungan['Label'].values

# Pembagian data menjadi data pelatihan dan data pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi model Naive Bayes
model = MultinomialNB()

# Pelatihan model Naive Bayes dengan data pelatihan
model.fit(X_train, y_train)

# Prediksi label kelas pada data pengujian
y_pred = model.predict(X_test)

# Mengukur akurasi model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi: {:.2f}%".format(accuracy * 100))

Akurasi: 52.76%


## K-Nearest Neighbors

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Inisialisasi model KNN dengan jumlah tetangga (n_neighbors) yang diinginkan
n_neighbors = 5  # Misalnya, menggunakan 5 tetangga terdekat
model_knn = KNeighborsClassifier(n_neighbors=n_neighbors)

# Pelatihan model KNN dengan data pelatihan
model_knn.fit(X_train, y_train)

# Prediksi label kelas pada data pengujian
y_pred = model_knn.predict(X_test)

# Mengukur akurasi model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi: {:.2f}%".format(accuracy * 100))


Akurasi: 66.33%


## Menyimpan Model KNN

In [37]:
# import joblib
# import re  # Import modul regex

# # Load model dan fungsi-fungsi preprocessing
# tokenize_text = joblib.load('tokenize_text_function.joblib')
# remove_stopwords = joblib.load('remove_stopwords_function.joblib')
# tfidf_model = joblib.load('tfidf_model.joblib')  # Sesuaikan dengan model yang digunakan
# lda_model = joblib.load('lda_model.joblib')  # Sesuaikan dengan model yang digunakan
# knn_model = joblib.load('knn_model.joblib')  # Sesuaikan dengan model yang digunakan

# # Contoh data baru yang ingin Anda prediksi
# new_data = [
#     "Pada Kejuaraan Dunia Judo yang berlangsung di Tokyo, Jepang, atlet muda dari negara Brazil, Ana Silva, berhasil mempersembahkan medali emas untuk kategori 63kg putri. Dengan usia yang masih 21 tahun, prestasi ini menjadi tonggak sejarah bagi Silva yang berhasil mengalahkan lawan-lawannya dengan teknik dan ketangguhan dalam setiap pertandingan."
# ]

# # Clean Punctuation
# def clean_punct(text):
#     clean_tag = re.compile('@\S+')
#     clean_url = re.compile('https?:\/\/.*[\r\n]*')
#     clean_hastag = re.compile('#\S+')
#     clean_symbol = re.compile('[^a-zA-Z]')
#     text = clean_tag.sub('', str(text))
#     text = clean_url.sub('', text)
#     text = clean_hastag.sub(' ', text)
#     text = clean_symbol.sub(' ', text)
#     return text

# # Pra-Pemrosesan teks baru
# cleaned_data = [clean_punct(text) for text in new_data]

# # Tokenisasi dan penghapusan stopwords
# tokenized_data = [tokenize_text(text) for text in cleaned_data]

# # Mengonversi setiap elemen dalam stopword_removed menjadi string
# stopword_removed_str = []
# for tokens in stopword_removed:
#     if isinstance(tokens, list):
#         tokens = [token for sublist in tokens for token in sublist]
#     stopword_removed_str.append(' '.join(tokens) if tokens else "")

# # Gabungkan setiap token dalam stopword_removed_str
# joined_stopword_removed = [' '.join(tokens) for tokens in stopword_removed_str if tokens]


# # Gabungkan setiap token dalam stopword_removed_str
# joined_stopword_removed = [' '.join(tokens) for tokens in stopword_removed_str]

# # Transformasi TF-IDF pada data baru
# tfidf_new_data = tfidf_model.transform(joined_stopword_removed)

# # Transformasi LDA pada data baru
# lda_new_data = lda_model.transform(tfidf_new_data)

# # Prediksi dengan model KNN pada data baru yang telah diproses
# predicted = knn_model.predict(lda_new_data)

# # Tampilkan hasil prediksi
# print(predicted)
